In [19]:
import pandas as pd
import numpy as np
import sklearn 
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
path=r"E:\Downloads\preprocessd_data_cleaned - preprocessd_data_cleaned.csv"

In [5]:
df=pd.read_csv(path)
df

,gender,age,no_of_days_subscribed,multi_screen,mail_subscribed,weekly_mins_watched,minimum_daily_mins,weekly_max_night_mins,videos_watched,customer_support_calls,churn
0,0,-0.264643,-0.946659,0,0,-1.508785,0.722258,-0.944404,-1.403000,-0.415473,0
1,0,0.029654,1.235009,0,0,0.304821,-0.901748,-0.688523,-0.599124,0.347522,0
2,0,2.580235,0.658246,0,0,-2.266627,0.613991,-0.483818,-1.403000,2.636507,1
3,0,-1.441834,0.783629,0,1,0.638123,-0.252146,0.079121,-0.197185,1.110517,0
4,0,0.127754,2.288228,0,0,-0.333851,0.253101,-0.893228,1.008630,-0.415473,0
...,...,...,...,...,...,...,...,...,...,...,...
3401,1,-0.805656,0.479710,0,0,0.887802,0.552184,0.865765,-0.495634,-0.415473,1
3402,0,0.477826,0.674425,0,0,2.038061,-0.931071,0.567257,2.100185,0.235227,1
3403,0,-0.550521,0.426099,0,1,-0.410669,0.344847,-0.729485,-0.403904,1.873512,1
3404,0,0.004651,-0.444637,0,0,1.359751,-0.847121,-0.715010,-0.197185,-1.178468,1
3405,0,-0.057028,0.317748,0,0,2.844852,0.098115,-0.550251,0.606692,-1.178468,1

In [7]:
X=df.drop('churn',axis=1)
y=df['churn']

In [9]:
X

,gender,age,no_of_days_subscribed,multi_screen,mail_subscribed,weekly_mins_watched,minimum_daily_mins,weekly_max_night_mins,videos_watched,customer_support_calls
0,0,-0.264643,-0.946659,0,0,-1.508785,0.722258,-0.944404,-1.403000,-0.415473
1,0,0.029654,1.235009,0,0,0.304821,-0.901748,-0.688523,-0.599124,0.347522
2,0,2.580235,0.658246,0,0,-2.266627,0.613991,-0.483818,-1.403000,2.636507
3,0,-1.441834,0.783629,0,1,0.638123,-0.252146,0.079121,-0.197185,1.110517
4,0,0.127754,2.288228,0,0,-0.333851,0.253101,-0.893228,1.008630,-0.415473
...,...,...,...,...,...,...,...,...,...,...
3401,1,-0.805656,0.479710,0,0,0.887802,0.552184,0.865765,-0.495634,-0.415473
3402,0,0.477826,0.674425,0,0,2.038061,-0.931071,0.567257,2.100185,0.235227
3403,0,-0.550521,0.426099,0,1,-0.410669,0.344847,-0.729485,-0.403904,1.873512
3404,0,0.004651,-0.444637,0,0,1.359751,-0.847121,-0.715010,-0.197185,-1.178468
3405,0,-0.057028,0.317748,0,0,2.844852,0.098115,-0.550251,0.606692,-1.178468

In [11]:
y

0       0
1       0
2       1
3       0
4       0
       ..
3401    1
3402    1
3403    1
3404    1
3405    1
Name: churn, Length: 3406, dtype: int64

In [15]:
df.shape

(3406, 11)

In [17]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [21]:
from sklearn.tree import DecisionTreeClassifier

In [23]:
dt = DecisionTreeClassifier(random_state=42)

In [25]:
param_grid = {
    'max_depth': [3,5,7,10],
    'max_features': ['sqrt','log2'],
    'criterion': ['gini','entropy'],
    'splitter': ['best','random']
}

In [31]:
from sklearn.model_selection import GridSearchCV

grid = GridSearchCV(
    estimator=dt,
    param_grid=param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

In [33]:
grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=42), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [3, 5, 7, 10],
                         'max_features': ['sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             scoring='accuracy')

In [35]:
print("Best Parameters:", grid.best_params_)
print("Best CV Score:", grid.best_score_)

Best Parameters: {'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'splitter': 'best'}
Best CV Score: 0.8293045062061521

In [43]:
best_model = grid.best_estimator_

In [45]:
from sklearn.metrics import accuracy_score, classification_report

y_pred = best_model.predict(X_test)

print("Test Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Test Accuracy: 0.8401759530791789
              precision    recall  f1-score   support

           0       0.82      0.87      0.85       341
           1       0.86      0.81      0.83       341

    accuracy                           0.84       682
   macro avg       0.84      0.84      0.84       682
weighted avg       0.84      0.84      0.84       682

In [47]:
results = pd.DataFrame(grid.cv_results_)
results[['params','mean_test_score']].sort_values(
    by='mean_test_score', ascending=False
).head()

                                               params  mean_test_score
14  {'criterion': 'gini', 'max_depth': 10, 'max_fe...         0.829305
12  {'criterion': 'gini', 'max_depth': 10, 'max_fe...         0.829305
30  {'criterion': 'entropy', 'max_depth': 10, 'max...         0.822690
28  {'criterion': 'entropy', 'max_depth': 10, 'max...         0.822690
10  {'criterion': 'gini', 'max_depth': 7, 'max_fea...         0.768747