## KNN

In [4]:
import pandas as pd
import numpy as np
import sklearn 
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
path=r"E:\Downloads\preprocessd_data_cleaned - preprocessd_data_cleaned.csv"

In [8]:
df=pd.read_csv(path)
df

,gender,age,no_of_days_subscribed,multi_screen,mail_subscribed,weekly_mins_watched,minimum_daily_mins,weekly_max_night_mins,videos_watched,customer_support_calls,churn
0,0,-0.264643,-0.946659,0,0,-1.508785,0.722258,-0.944404,-1.403000,-0.415473,0
1,0,0.029654,1.235009,0,0,0.304821,-0.901748,-0.688523,-0.599124,0.347522,0
2,0,2.580235,0.658246,0,0,-2.266627,0.613991,-0.483818,-1.403000,2.636507,1
3,0,-1.441834,0.783629,0,1,0.638123,-0.252146,0.079121,-0.197185,1.110517,0
4,0,0.127754,2.288228,0,0,-0.333851,0.253101,-0.893228,1.008630,-0.415473,0
...,...,...,...,...,...,...,...,...,...,...,...
3401,1,-0.805656,0.479710,0,0,0.887802,0.552184,0.865765,-0.495634,-0.415473,1
3402,0,0.477826,0.674425,0,0,2.038061,-0.931071,0.567257,2.100185,0.235227,1
3403,0,-0.550521,0.426099,0,1,-0.410669,0.344847,-0.729485,-0.403904,1.873512,1
3404,0,0.004651,-0.444637,0,0,1.359751,-0.847121,-0.715010,-0.197185,-1.178468,1
3405,0,-0.057028,0.317748,0,0,2.844852,0.098115,-0.550251,0.606692,-1.178468,1

In [10]:
X=df.drop('churn',axis=1)
y=df['churn']

In [12]:
X

,gender,age,no_of_days_subscribed,multi_screen,mail_subscribed,weekly_mins_watched,minimum_daily_mins,weekly_max_night_mins,videos_watched,customer_support_calls
0,0,-0.264643,-0.946659,0,0,-1.508785,0.722258,-0.944404,-1.403000,-0.415473
1,0,0.029654,1.235009,0,0,0.304821,-0.901748,-0.688523,-0.599124,0.347522
2,0,2.580235,0.658246,0,0,-2.266627,0.613991,-0.483818,-1.403000,2.636507
3,0,-1.441834,0.783629,0,1,0.638123,-0.252146,0.079121,-0.197185,1.110517
4,0,0.127754,2.288228,0,0,-0.333851,0.253101,-0.893228,1.008630,-0.415473
...,...,...,...,...,...,...,...,...,...,...
3401,1,-0.805656,0.479710,0,0,0.887802,0.552184,0.865765,-0.495634,-0.415473
3402,0,0.477826,0.674425,0,0,2.038061,-0.931071,0.567257,2.100185,0.235227
3403,0,-0.550521,0.426099,0,1,-0.410669,0.344847,-0.729485,-0.403904,1.873512
3404,0,0.004651,-0.444637,0,0,1.359751,-0.847121,-0.715010,-0.197185,-1.178468
3405,0,-0.057028,0.317748,0,0,2.844852,0.098115,-0.550251,0.606692,-1.178468

In [14]:
y

0       0
1       0
2       1
3       0
4       0
       ..
3401    1
3402    1
3403    1
3404    1
3405    1
Name: churn, Length: 3406, dtype: int64

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [18]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV

knn = KNeighborsClassifier()

param_grid_knn = {
    'n_neighbors':[3,5,7,9,11],
    'weights':['uniform','distance'],
    'metric':['euclidean','manhattan']
}

grid_knn = GridSearchCV(
    estimator=knn,
    param_grid=param_grid_knn,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

grid_knn.fit(X_train,y_train)

print("Best Parameters:",grid_knn.best_params_)
print("Best Score:",grid_knn.best_score_)

Best Parameters: {'metric': 'manhattan', 'n_neighbors': 3, 'weights': 'distance'}
Best Score: 0.898677819751754

In [28]:
best_model = grid_knn.best_estimator_
best_model

KNeighborsClassifier(metric='manhattan', n_neighbors=3, weights='distance')

In [26]:
from sklearn.metrics import accuracy_score, classification_report

y_pred = best_model.predict(X_test)

print("Test Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Test Accuracy: 0.8900293255131965
              precision    recall  f1-score   support

           0       0.99      0.79      0.88       341
           1       0.82      0.99      0.90       341

    accuracy                           0.89       682
   macro avg       0.91      0.89      0.89       682
weighted avg       0.91      0.89      0.89       682

## Logistic Regression

In [32]:
from sklearn.linear_model import LogisticRegression

log = LogisticRegression(max_iter=500)

param_grid_log = {
    'penalty':['l1','l2'],
    'C':[0.01,0.1,1,10],
    'solver':['liblinear']
}

grid_log = GridSearchCV(
    estimator=log,
    param_grid=param_grid_log,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

grid_log.fit(X_train,y_train)

print("Best Parameters:",grid_log.best_params_)
print("Best Score:",grid_log.best_score_)

Best Parameters: {'C': 0.1, 'penalty': 'l1', 'solver': 'liblinear'}
Best Score: 0.7305545062061523

In [36]:
best_model=grid_log.best_estimator_
best_model

LogisticRegression(C=0.1, max_iter=500, penalty='l1', solver='liblinear')

In [40]:
from sklearn.metrics import accuracy_score, classification_report

y_pred = best_model.predict(X_test)

print("Test Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Test Accuracy: 0.7390029325513197
              precision    recall  f1-score   support

           0       0.75      0.72      0.73       341
           1       0.73      0.76      0.74       341

    accuracy                           0.74       682
   macro avg       0.74      0.74      0.74       682
weighted avg       0.74      0.74      0.74       682

## Naive Byes

In [44]:
from sklearn.naive_bayes import GaussianNB

nb = GaussianNB()

param_grid_nb = {
    'var_smoothing': np.logspace(0,-9,100)
}

grid_nb = GridSearchCV(
    estimator=nb,
    param_grid=param_grid_nb,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

grid_nb.fit(X_train,y_train)

print("Best Parameters:",grid_nb.best_params_)
print("Best Score:",grid_nb.best_score_)

Best Parameters: {'var_smoothing': 0.12328467394420659}
Best Score: 0.7657906098219104

In [48]:
best_model=grid_nb.best_estimator_

In [50]:
y_predict=best_model.predict(X_test)

In [52]:
from sklearn.metrics import accuracy_score, classification_report

y_pred = best_model.predict(X_test)

print("Test Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Test Accuracy: 0.7697947214076246
              precision    recall  f1-score   support

           0       0.77      0.77      0.77       341
           1       0.77      0.77      0.77       341

    accuracy                           0.77       682
   macro avg       0.77      0.77      0.77       682
weighted avg       0.77      0.77      0.77       682

## Compare all three models

In [56]:
print("KNN:",grid_knn.best_score_)
print("Logistic:",grid_log.best_score_)
print("Naive Bayes:",grid_nb.best_score_)

KNN: 0.898677819751754
Logistic: 0.7305545062061523
Naive Bayes: 0.7657906098219104